### ISSUE TITLE
Error in create first page

### ISSUE THREAD

**Issue by paulafernanda** [Open-E-WEB/django-powerpages#8]
I instaled the package and after created the page appear the error below:

Error during template rendering

In template /home/paula/.virtualenvs/integrar-cms/local/lib/python2.7/site-packages/powerpages/templates/powerpages/admin/includes/website_edit_button.html, error at line 2
Invalid block tag on line 2: 'page_url'. Did you forget to register or load this tag?

Can you help me?

**Comment by rydzopene** [comment]
Hi paulafernanda
Sorry for delay, this bug was fixed some time ago, but wasn't uploaded on pypi.
Please make sure you have version v0.0.7 or higher - available from pip since now (before the only way was to manually download source code from github).
Feel free to ask any questions, we will try to reply as soon as possible.

We will close this issue once we hear from you that it works now (or let's say - after 2 weeks)
 
Best regards
Open-E
